
/**
 * src/services/ai/governance/GovernanceTypes.ts
 * 
 * Defines the schema for the AI Compliance & Governance Layer.
 * 
 * PHILOSOPHY:
 * This layer acts as the "Black Box Recorder" for the AI. 
 * Every significant decision—whether a budget shift, a bot action, or a strategic suggestion—
 * must be typed, sourced, and recorded here before execution.
 */

export type DecisionSource = 
  | "RULE_ENGINE"       // Phase 10.2: Deterministic heuristics
  | "MEMORY_ENGINE"     // Phase 10.3: Historical pattern matching
  | "PORTFOLIO_ENGINE"; // Future: Multi-campaign optimization

export type DecisionType =
  | "BUDGET_REALLOCATION" // Money movement
  | "BOT_ACTION"          // Content creation / Engagement
  | "CAMPAIGN_STRATEGY"   // High-level direction change
  | "AI_SUGGESTION";      // Advisory content

export type DecisionStatus =
  | "PROPOSED"    // Generated by AI, waiting
  | "APPROVED"    // Human stamped
  | "REJECTED"    // Human denied
  | "OVERRIDDEN"  // Executed with modified parameters
  | "EXECUTED";   // Auto-executed (if policy allows)

/**
 * The immutable record of a specific AI decision event.
 * Maps to a database row in 'DecisionAuditLogs'.
 */
export interface DecisionAuditEntry {
  id: string;
  timestamp: Date;
  
  // Categorization
  decisionType: DecisionType;
  source: DecisionSource;
  
  // The "What" and "Why"
  description: string;
  reasoning: string;
  
  // AI Metacognition
  confidenceScore: number; // 0.0 to 1.0
  
  // Context Links
  relatedCampaignId?: string;
  relatedBotId?: string;
  
  // Traceability: Which patterns from Phase 10.3 influenced this?
  influencedByPatterns?: string[]; // IDs of StrategyPatterns
  
  // Lifecycle
  status: DecisionStatus;
  approvalRecord?: ApprovalRecord;
}

/**
 * Sub-record for human-in-the-loop actions.
 */
export interface ApprovalRecord {
  decisionId: string;
  approvedBy: string; // User ID or Name
  approvedAt: Date;
  notes?: string;     // Optional context for the approval/rejection
}
